fix: Fixed import error by changing ES bulk import params
```text
org.apache.spark.util.TaskCompletionListenerException: is.hail.relocated.org.elasticsearch.hadoop.rest.EsHadoopRemoteException: circuit_breaking_exception: [parent] Data too large, data for [<http_request>] would be [1052053504/1003.3mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1052053504/1003.3mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=23409/22.8kb, in_flight_requests=2089882/1.9mb, accounting=5473848/5.2mb]
null

Previous exception in task: is.hail.relocated.org.elasticsearch.hadoop.rest.EsHadoopRemoteException: circuit_breaking_exception: [parent] Data too large, data for [<http_request>] would be [1052046818/1003.3mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1049956352/1001.3mb], new bytes reserved: [2090466/1.9mb], usages [request=0/0b, fielddata=23409/22.8kb, in_flight_requests=4180348/3.9mb, accounting=5473848/5.2mb]
{"index":{"_id":"1-243211820-T-A"}}
```